### ISSUE TITLE
thread safe?

### ISSUE THREAD

**Issue by mwu153** [ivanakcheurov/ntextcat#2]
is the RankedLanguageIdentifierFactory and RankedLanguageIdentifier thread safe?

**Comment by ivanakcheurov** [comment]
If you use different instances in each thread, then it is thread-safe.
If you use the same RankedLanguageIdentifier instance for language identification (`Identify`) method, then it should be also thread-safe.
If you get a bug with this, please create an issue with the full code and exact steps to reproduce the bug.
