### ISSUE TITLE
.NetStandard Compatibility

### ISSUE THREAD

**Issue by YairHalberstadt** [ivanakcheurov/ntextcat#5]
Looking at your library, it has no dependencies, and  so should be very simple (less than a couple of hours work) to convert to .Net Standard.
Do you have any plans to do this?

**Comment by YairHalberstadt** [comment]
I've created a .net standard version, and it's now available on Nuget as NTextCatCore.

If you do ever create an official version, I'd be happy to remove mine and allow you to publish yours.

**Comment by ivanakcheurov** [comment]
Hi YairHalberstadt,
Thank you for your package.
I have updated NTextCat to .NET Standard 2.0 too.
Please check if the latest version works for you.
Thanks again :)
