### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by Seany84** [ivanakcheurov/ntextcat#6]
Hi Ivan,

Are you accepting any PR's or plan to do a .net core/standard version?

Would you consider allowing other contributors on this repo?

Thanks and well cone on your port, it is a great accomplishment.

**Comment by ivanakcheurov** [comment]
I haven't been active on the project for a while.
Yes, I do accept PRs, would be much appreciated!

**Comment by ivanakcheurov** [comment]
Hi @Seany84 
Thank you for your useful contribution.
I have updated NTextCat to .NET Standard 2.0.
Please check if it works for you.
Thanks!
